language: node_js
node_js: "12"
cache: yarn
jobs:
  include:
    - stage: test
      script:
        - "npm run test"
stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master
